# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lora_tool_main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 252)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bt_lora_send = QtWidgets.QPushButton(self.centralwidget)
        self.bt_lora_send.setGeometry(QtCore.QRect(290, 50, 71, 31))
        self.bt_lora_send.setMinimumSize(QtCore.QSize(0, 0))
        self.bt_lora_send.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.bt_lora_send.setObjectName("bt_lora_send")
        self.bt_lora_change_fre = QtWidgets.QPushButton(self.centralwidget)
        self.bt_lora_change_fre.setGeometry(QtCore.QRect(290, 10, 71, 31))
        self.bt_lora_change_fre.setMinimumSize(QtCore.QSize(0, 0))
        self.bt_lora_change_fre.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.bt_lora_change_fre.setObjectName("bt_lora_change_fre")
        self.bt_lora_save = QtWidgets.QPushButton(self.centralwidget)
        self.bt_lora_save.setGeometry(QtCore.QRect(290, 110, 71, 31))
        self.bt_lora_save.setMinimumSize(QtCore.QSize(0, 0))
        self.bt_lora_save.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.bt_lora_save.setObjectName("bt_lora_save")
        self.bt_lora_clear = QtWidgets.QPushButton(self.centralwidget)
        self.bt_lora_clear.setGeometry(QtCore.QRect(380, 110, 71, 31))
        self.bt_lora_clear.setMinimumSize(QtCore.QSize(0, 0))
        self.bt_lora_clear.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.bt_lora_clear.setObjectName("bt_lora_clear")
        self.bt_lora_default = QtWidgets.QPushButton(self.centralwidget)
        self.bt_lora_default.setGeometry(QtCore.QRect(290, 150, 71, 31))
        self.bt_lora_default.setMinimumSize(QtCore.QSize(0, 0))
        self.bt_lora_default.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.bt_lora_default.setObjectName("bt_lora_default")
        self.bt_lora_cfgdo = QtWidgets.QPushButton(self.centralwidget)
        self.bt_lora_cfgdo.setGeometry(QtCore.QRect(290, 190, 71, 31))
        self.bt_lora_cfgdo.setMinimumSize(QtCore.QSize(0, 0))
        self.bt_lora_cfgdo.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.bt_lora_cfgdo.setObjectName("bt_lora_cfgdo")
        self.bt_lora_cfgget = QtWidgets.QPushButton(self.centralwidget)
        self.bt_lora_cfgget.setGeometry(QtCore.QRect(380, 150, 71, 31))
        self.bt_lora_cfgget.setMinimumSize(QtCore.QSize(0, 0))
        self.bt_lora_cfgget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.bt_lora_cfgget.setObjectName("bt_lora_cfgget")
        self.ser_comboBox__fre = QtWidgets.QComboBox(self.centralwidget)
        self.ser_comboBox__fre.setGeometry(QtCore.QRect(370, 10, 91, 31))
        self.ser_comboBox__fre.setObjectName("ser_comboBox__fre")
        self.ser_comboBox__fre.addItem("")
        self.ser_comboBox__fre.addItem("")
        self.ser_comboBox__fre.addItem("")
        self.ser_comboBox__fre.addItem("")
        self.lab_senddata = QtWidgets.QLineEdit(self.centralwidget)
        self.lab_senddata.setGeometry(QtCore.QRect(370, 50, 91, 31))
        self.lab_senddata.setObjectName("lab_senddata")
        self.bt_lora_rcv_clear = QtWidgets.QPushButton(self.centralwidget)
        self.bt_lora_rcv_clear.setGeometry(QtCore.QRect(380, 190, 71, 31))
        self.bt_lora_rcv_clear.setMinimumSize(QtCore.QSize(0, 0))
        self.bt_lora_rcv_clear.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.bt_lora_rcv_clear.setObjectName("bt_lora_rcv_clear")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setEnabled(True)
        self.textBrowser.setGeometry(QtCore.QRect(10, 50, 261, 171))
        self.textBrowser.setObjectName("textBrowser")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(12, 12, 261, 31))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ser_bt_find = QtWidgets.QPushButton(self.widget)
        self.ser_bt_find.setObjectName("ser_bt_find")
        self.horizontalLayout.addWidget(self.ser_bt_find)
        self.ser_comboBox = QtWidgets.QComboBox(self.widget)
        self.ser_comboBox.setObjectName("ser_comboBox")
        self.horizontalLayout.addWidget(self.ser_comboBox)
        self.ser_bt_open = QtWidgets.QPushButton(self.widget)
        self.ser_bt_open.setObjectName("ser_bt_open")
        self.horizontalLayout.addWidget(self.ser_bt_open)
        self.ser_bt_close = QtWidgets.QPushButton(self.widget)
        self.ser_bt_close.setObjectName("ser_bt_close")
        self.horizontalLayout.addWidget(self.ser_bt_close)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setStatusTip("")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bt_lora_send.setText(_translate("MainWindow", "发送数据"))
        self.bt_lora_change_fre.setText(_translate("MainWindow", "修改频率"))
        self.bt_lora_save.setText(_translate("MainWindow", "保存配置"))
        self.bt_lora_clear.setText(_translate("MainWindow", "清除配置"))
        self.bt_lora_default.setText(_translate("MainWindow", "恢复默认"))
        self.bt_lora_cfgdo.setText(_translate("MainWindow", "应用配置"))
        self.bt_lora_cfgget.setText(_translate("MainWindow", "查询配置"))
        self.ser_comboBox__fre.setItemText(0, _translate("MainWindow", "470300000"))
        self.ser_comboBox__fre.setItemText(1, _translate("MainWindow", "470500000"))
        self.ser_comboBox__fre.setItemText(2, _translate("MainWindow", "470700000"))
        self.ser_comboBox__fre.setItemText(3, _translate("MainWindow", "470900000"))
        self.lab_senddata.setText(_translate("MainWindow", "112233"))
        self.bt_lora_rcv_clear.setText(_translate("MainWindow", "清空接收"))
        self.ser_bt_find.setText(_translate("MainWindow", "串口搜索"))
        self.ser_bt_open.setText(_translate("MainWindow", "打开"))
        self.ser_bt_close.setText(_translate("MainWindow", "关闭"))

